# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwD8OFx1rv86wMp1stV6VW0QJ0iLHkG4

## Predictive Analytics - Bank Customer Churn

### Deskripsi Proyek
Bank XYZ mengalami tingkat churn pelanggan yang cukup tinggi dalam beberapa tahun terakhir. Proyek ini bertujuan untuk memprediksi apakah seorang pelanggan akan berhenti (churn) berdasarkan data historis mereka. Dengan pemodelan yang tepat, pihak bank dapat menargetkan pelanggan berisiko tinggi dan melakukan upaya retensi secara efektif.

### 1. Import Library
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

"""### 2. Data Understanding
Data Understanding merupakan proses memahami informasi dalam data dan menentukan kualitas data tersebut.

#### 2.1 Data Loading
Data Loading merupakan tahap untuk memuat dataset yang akan digunakan agar dataset lebih mudah dipahami

*dataset yang digunakan dalam proyek ini:*

https://www.kaggle.com/datasets/mathchi/churn-for-bank-customers
"""

df = pd.read_csv("churn.csv")

"""**Insight**

Memuat dataset obesitas menggunakan fungsi pd.read_csv(). Data diambil dari file CSV yang berisi 10000 catatan dan 14 fitur. Pemeriksaan awal dilakukan untuk melihat beberapa baris pertama dan terakhir guna memastikan data berhasil dimuat dengan benar.

#### 2.2 Exploratory Data Analysis

Eksploratori data merupakan langkah pertama dalam menganalisa data yang bertujuan untuk mengenali ciri - ciri data, menemukan pola atau ketidakwajaran, dan menguji hipotesis yang ada. Tahap ini biasanya melibatkan penggunaan teknik statistik dan visualisasi grafik guna membantu dalam pemahaman data.

##### 2.2.1 EDA - Deskripsi Variabel
"""

df.head()

df.tail()

df.info()

df.describe()

"""#### 2.2.2 EDA - Menangani Missing Value dan Menangani Outliers"""

df.isnull().sum()

df.duplicated()

df.duplicated().sum()

df =df.drop_duplicates()

"""**Insight**

Dilakukan pemeriksaan missing values dan duplikasi. Hasil pengecekan menunjukkan bahwa tidak ada missing values, namun terdapat beberapa duplikat yang kemudian dihapus untuk menjaga keunikan data.
"""

df.columns

# Visualisasi distribusi Age dan Balance
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Boxplot untuk Age
sns.boxplot(y=df['Age'], ax=axes[0], color='darkblue')
axes[0].set_title('Age Distribution')
axes[0].set_ylabel('Age')

# Boxplot untuk Balance
sns.boxplot(y=df['Balance'], ax=axes[1], color='darkgreen')
axes[1].set_title('Balance Distribution')
axes[1].set_ylabel('Balance')

plt.tight_layout()
plt.show()

"""#### 2.2.3 EDA - Univariate Analysis"""

# 2.1 Univariate Analysis
# -------------------------
# Visualisasi distribusi variabel numerik dengan histogram
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Memilih kolom numerik dari dataset
numeric_cols = df.select_dtypes(include=[np.number]).columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(4, 4, i)
    sns.histplot(df[col], bins=30, kde=True, color='steelblue')
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Visualisasi count plot untuk variabel kategorikal
cat_cols = ['Gender', 'Geography', 'HasCrCard', 'IsActiveMember', 'NumOfProducts']
plt.figure(figsize=(15, 10))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(3, 2, i)
    sns.countplot(x=col, hue=col, data=df, palette="viridis")
    plt.title(f"Count of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
plt.tight_layout()
plt.show()

"""#### 2.2.4 Multivariate Analysis"""

# Menghitung crosstab antara IsActiveMember dan Exited
crosstab = pd.crosstab(df['IsActiveMember'], df['Exited'])

# Membuat plot bar stacked
crosstab.plot(kind='bar', stacked=True, colormap='coolwarm')
plt.title('Active Membership vs. Churn Levels')
plt.xlabel('Active Member (1 = Yes, 0 = No)')
plt.ylabel('Count')
plt.xticks(rotation=0)  # Mengatur rotasi label sumbu x
plt.legend(title='Exited (1 = Yes, 0 = No)')
plt.show()

# Membuat violin plot untuk NumOfProducts dan Exited
sns.violinplot(x='NumOfProducts', y='Exited', data=df, palette='muted')
plt.title('Number of Products vs. Churn Levels')
plt.xlabel('Number of Products')
plt.ylabel('Churn (1 = Yes, 0 = No)')
plt.xticks(rotation=0)  # Mengatur rotasi label sumbu x
plt.show()

# Membuat boxplot untuk NumOfProducts dan Balance berdasarkan Exited
sns.boxplot(x='NumOfProducts', y='Balance', data=df, hue='Exited', palette='coolwarm')
plt.title('Number of Products vs. Balance by Churn Levels')
plt.xlabel('Number of Products')
plt.ylabel('Balance')
plt.legend(title='Exited (1 = Yes, 0 = No)')
plt.show()

# Membuat strip plot untuk NumOfProducts dan Balance berdasarkan Exited
sns.stripplot(x='NumOfProducts', y='Balance', hue='Exited', data=df, palette='coolwarm', jitter=True)
plt.title('Number of Products vs. Balance by Churn Levels')
plt.xlabel('Number of Products')
plt.ylabel('Balance')
plt.legend(title='Exited (1 = Yes, 0 = No)')
plt.show()

# Membuat count plot untuk Geography berdasarkan Exited
sns.countplot(x='Geography', hue='Exited', data=df, palette='Set2')
plt.title('Geography Distribution by Churn Levels')
plt.xlabel('Geography')
plt.ylabel('Count')
plt.legend(title='Exited (1 = Yes, 0 = No)')
plt.show()

# 2.2 Multivariate Analysis
# ---------------------------
# Visualisasi pairplot untuk melihat hubungan antara variabel numerik
# Misalkan numeric_cols adalah daftar kolom numerik dalam dataset
numeric_cols = ['Age', 'Balance', 'NumOfProducts', 'CreditScore', 'EstimatedSalary']  # Ganti dengan kolom yang relevan

# Visualisasi pairplot untuk melihat hubungan antara variabel numerik
sns.pairplot(df[numeric_cols], diag_kind='kde', corner=True)
plt.suptitle("Pairplot for Numeric Features", y=1.02)
plt.show()

# Visualisasi Heatmap korelasi antar fitur
plt.figure(figsize=(10, 6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

"""**Insight**

Analisis eksplorasi data dilakukan untuk memahami distribusi dan hubungan antar variabel. Dari histogram, terlihat sebaran nilai pada setiap variabel numerik, sedangkan count plot menunjukkan frekuensi kategori pada variabel kategorikal. Insight penting yang diperoleh antara lain: tidak ada missing value, distribusi data cukup simetris pada sebagian besar fitur, dan terdapat beberapa outlier yang mungkin memerlukan perhatian lebih lanjut.

### 3. Data Preparation
Persiapan data adalah langkah yang dilakukan untuk mengolah data agar siap digunakan dalam tahap pembuatan model Machine Learning.

#### 3.1 Encoding Variabel Kategorikal
"""

# Misalkan df adalah DataFrame Anda
le = LabelEncoder()

# Daftar kolom yang akan di-encode
categorical_cols = [
    "Gender",  # Contoh kolom untuk jenis kelamin
    "Geography",  # Contoh kolom untuk lokasi geografis
    "Exited"  # Kolom target untuk churn
]

# Melakukan encoding untuk setiap kolom dalam daftar
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

# Menampilkan DataFrame setelah encoding
print(df.head())

"""#### 3.2 Pemisahan Fitur Target"""

# Misalkan df adalah DataFrame Anda
# Define x and y before encoding
x = df.drop(["Exited"], axis=1)  # Ganti "Exited" dengan kolom target yang sesuai
y = df["Exited"]  # Ganti "Exited" dengan kolom target yang sesuai

# Initialize label encoder
encoders = {}  # Dictionary to store encoders for each categorical column

# Encode only categorical columns
for col in x.columns:
    if x[col].dtype == 'object' or x[col].dtype.name == 'category':
        le = LabelEncoder()  # Create a new LabelEncoder for each column
        x[col] = le.fit_transform(x[col])
        encoders[col] = le  # Store the encoder for future use

print("Categorical encoding completed!")

print(x.dtypes)

# Create a LabelEncoder instance
le = LabelEncoder()

# Identify categorical columns (bins)
categorical_cols = [col for col in x.columns if x[col].dtype.name == 'category']

# Convert categorical columns to numeric
for col in categorical_cols:
    x[col] = le.fit_transform(x[col])

"""**Insight**

Mengubah variabel kategorikal ke format numerik menggunakan LabelEncoder

#### 3.3 Train-Test-Split
"""

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Standardization
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

"""#### 3.4 Standarisasi"""

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

print(x_train.dtype)

"""**Insight**

menstandarisasi variabel numerik dengan StandardScaler. Transformasi ini penting agar model machine learning dapat memproses semua data secara konsisten.

#### 4. Model Development
Pengembangan model adalah fase di mana algoritma machine learning diterapkan untuk menyelesaikan permasalahan yang telah diidentifikasi pada tahap pemahaman bisnis.
"""

# Define models dictionary
models = {
    "Random Forest Classifier": RandomForestClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Ada Boost Classifier": AdaBoostClassifier(),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "Logistic Regression": LogisticRegression(max_iter=1000)
}

# Verifikasi dictionary model
print("Defined Models:")
print(models)

# Dictionary untuk menyimpan performa masing-masing model
results = {}

# Loop untuk training dan evaluasi setiap model
for name, model in models.items():
    # Training model
    model.fit(x_train, y_train)

    # Prediksi pada data testing
    y_pred = model.predict(x_test)

    # Menghitung metrik evaluasi
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    # Simpan hasil evaluasi pada dictionary
    results[name] = {
       "accuracy": acc,
       "precision": prec,
       "recall": rec,
       "f1_score": f1,
       "confusion_matrix": cm
    }

    # Print hasil evaluasi untuk tiap model
    print(f"\n{name}:")
    print(f"  Accuracy: {acc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall: {rec:.4f}")
    print(f"  F1 Score: {f1:.4f}")
    print("  Confusion Matrix:")
    print(cm)

# Menentukan model terbaik berdasarkan akurasi (atau metrik lain sesuai kebutuhan)
best_model_name = max(results, key=lambda x: results[x]["accuracy"])
print(f"\nBest Model by Accuracy: {best_model_name}")

"""**Insight**

Berbagai model dikembangkan untuk melakukan klasifikasi. Model-model yang digunakan antara lain Random Forest, Decision Tree, AdaBoost, KNN, Gradient Boosting, dan Logistic Regression. Evaluasi dilakukan dengan menghitung metrik seperti accuracy, precision, recall, F1 score, dan confusion matrix. Model Random Forest menunjukkan performa terbaik dengan akurasi tertinggi, yang mendukung keandalan model dalam membantu identifikasi individu berisiko tinggi.
"""

# Visualisasi Confusion Matrix untuk model terbaik
best_cm = results[best_model_name]["confusion_matrix"]

plt.figure(figsize=(8, 6))
sns.heatmap(best_cm, annot=True, fmt='d', cmap='Blues')
plt.title(f"Confusion Matrix for {best_model_name}")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

"""**Insight**

Hasil evaluasi model divisualisasikan menggunakan heatmap untuk confusion matrix dan bar chart untuk perbandingan akurasi antar model. Visualisasi ini memudahkan analisis perbandingan kinerja setiap model, sehingga model dengan performa terbaik dapat diidentifikasi secara objektif.

**Conclusion**
Evaluasi model dilakukan untuk menentukan model yang paling sesuai dengan tujuan bisnis. Hasil evaluasi menunjukkan bahwa:

- Random Forest Classifier memiliki akurasi tertinggi (sekitar 87.04%) serta metrik evaluasi lain yang sangat baik, menjadikannya kandidat terbaik untuk prediksi tingkat obesitas.
- Model lain juga menunjukkan performa yang baik, namun sedikit di bawah model Random Forest.
- Decision Tree Classifier dan Logistic Regression menunjukkan performa yang lebih rendah dan tidak konsisten.
"""